#Create Portainer config "wordpress-mariadb"
#    
#    ```
#    [mysqld]
#    character-set-client-handshake = FALSE
#    character-set-server = utf8mb4
#    collation-server = utf8mb4_unicode_ci
#    server-id        = 1
#    expire_logs_days = 10
#    binlog_format    = row
#    log_bin          = /var/log/mysql/mysql-bin
#     
#    [mysql]
#    default-character-set = utf8mb4
#    ```
#  
#Stack Environment Variables
#    
#DOMAIN=subdomain.example.domain
#NODE=manager, worker1, etc
#STACK=name of this stack for traefik reference
#MYSQL_ROOT_PASSWORD=somepassword
#MYSQL_PASSWORD=somepassword
#SQLBAK_KEY=sqlbak key

version: '3.8'

services:
  wp:
    image: wordpress
    volumes:
      - wp-data:/var/www/html
    networks:
      - internal-network
      - traefik-public
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=wordpress
    deploy:
      placement:
        constraints:
        - node.labels.$NODE == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.${STACK}_wp-http.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${STACK}_wp-http.entrypoints=http"
        - "traefik.http.routers.${STACK}_wp-http.middlewares=https-redirect"
        - "traefik.http.routers.${STACK}_wp-https.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${STACK}_wp-https.entrypoints=https"
        - "traefik.http.routers.${STACK}_wp-https.tls=true"
        - "traefik.http.routers.${STACK}_wp-https.tls.certresolver=le"
        - "traefik.http.services.${STACK}_wp.loadbalancer.server.port=80"

  mariadb:
    image: mariadb:10.5
    networks:
      - internal-network
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    configs:
      - source: wordpress-mariadb
        target: /etc/mysql/conf.d/wordpress.cnf
    volumes:
      - mariadb-vol:/var/lib/mysql
      - mariadb-logs:/var/log/mysql
    deploy:
      placement:
        constraints:
        - node.labels.$NODE == true

#  sqlbak:
#    image: pranasnet/sqlbak
#    volumes:
#      - sqlbak-data:/opt/sqlbak
#      - sqlbak-temp:/tmp/sqlbak
#      - mariadb-logs:/var/log/mysql
#      - wp-data:/wordpress
#    networks:
#      - internal-network
#    environment:
#      - sqlbak_key=${SQLBAK_KEY}
#      - sqlbak_name=${STACK}
#      - db_type=MYSQL
#      - user=root
#      - password=${MYSQL_ROOT_PASSWORD}
#      - host=mariadb
#      - port=3306
#    depends_on:
#      - mariadb
#    deploy:
#      placement:
#        constraints:
#        - node.labels.$NODE == true

volumes:
  wp-data:
  mariadb-vol:
  mariadb-logs:
#  sqlbak-data:
#  sqlbak-temp:

configs:
  wordpress-mariadb:
    external: true

networks:
  internal-network:
  traefik-public:
    external: true
