#To Setup Ignition Gateway Database Connection when in the WebUI
#    
#    - `JDBC Driver` - MariaDB
#    - `user` - db
#    - `URL` jdbc:db://mariadb:3306/db
#
#Stack Environment Variables
#    
#DOMAIN=subdomain.example.domain
#NODE=manager, worker1, etc
#STACK=name of this stack for traefik reference
#MYSQL_ROOT_PASSWORD=somepassword
#MYSQL_PASSWORD=somepassword
#IGPASSWORD=Ignition admin password

version: '3.8'

services:
  ignition:
    image:  kcollins/ignition
    volumes:
      - ignition-data:/var/lib/ignition/data
    networks:
      - internal-network
      - traefik-public
    environment:
      - GATEWAY_SYSTEM_NAME=${STACK}_ignition
      - GATEWAY_ADMIN_PASSWORD=${IGPASSWORD}
      - IGNITION_EDITION=full
      - IGNITION_STARTUP_DELAY=30
    deploy:
      placement:
        constraints:
          - node.labels.${NODE?Variable not set} == true
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.${STACK}_ignition-http.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${STACK}_ignition-http.entrypoints=http"
        - "traefik.http.routers.${STACK}_ignition-http.middlewares=https-redirect"
        - "traefik.http.routers.${STACK}_ignition-https.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${STACK}_ignition-https.entrypoints=https"
        - "traefik.http.routers.${STACK}_ignition-https.tls=true"
        - "traefik.http.routers.${STACK}_ignition-https.tls.certresolver=le"
        - "traefik.http.services.${STACK}_ignition.loadbalancer.server.port=8088"
        - "traefik.http.middlewares.${STACK}_ignition-path.replacepathregex.regex=^/main/StatusPing$$"
        - "traefik.http.middlewares.${STACK}_ignition-path.replacepathregex.replacement=/StatusPing"

  db:
    image:  mariadb
    volumes:
      - db_config:/config
      - db:/var/lib/mysql
    networks:
      - internal-network
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=db
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    deploy:
      placement:
        constraints:
          - node.labels.${NODE?Variable not set} == true

networks:
  internal-network:
  traefik-public:
    external: true

volumes:
  ignition-data:
  db_config:
  db:
